### ISSUE TITLE
java.util.ResourceBundle.getBundle throws ClassNotFoundException

### ISSUE THREAD

**Issue by gitounet** [ikvmnet/ikvm#194]
IKVM version 8.2.0.0

Runtime Environment:
    OS Version: Microsoft Windows NT 6.2.9200.0
    Runtime: .NET Framework CLR v4.0.30319.42000

I am facing a ClassNotFoundException when trying to load a  properties file using java.util.ResourceBundle. Could you help?

To reproduce:

•	Create a Java class named Reproducer with method:

`public static void reproduce() {
	ResourceBundle resourceBundle = ResourceBundle.getBundle("path/to/bundle", new Locale("en", "US"));
}`
    
•	Add file path/to/bundle_en.properties to Java classpath.
•	Build dll from Java sources.
•	Call Reproducer.reproduce() from .NET code:

Expected: getBundle returns a non null resourceBundle.

Actual:
`ClassNotFoundException : path/to/bundle
    at IKVM.Java.Externs.ikvm.runtime.AppDomainAssemblyClassLoader.findClass(Object thisObj, String name)
    at ikvm.runtime.AppDomainAssemblyClassLoader.findClass(String name)
    at java.lang.ClassLoader.loadClass(String name, Boolean resolve)
    at java.lang.ClassLoader.loadClass(String name)
    at java.util.ResourceBundle.Control.newBundle(String baseName, Locale locale, String format, ClassLoader loader, Boolean reload)
    at java.util.ResourceBundle.loadBundle(
    CacheKey cacheKey, List formats, Control control, Boolean reload)
    at java.util.ResourceBundle.findBundle(CacheKey cacheKey, List candidateLocales, List formats, Int32 index, Control control, ResourceBundle baseBundle)
    at java.util.ResourceBundle.findBundle(CacheKey cacheKey, List candidateLocales, List formats, Int32 index, Control control, ResourceBundle baseBundle)
    at java.util.ResourceBundle.findBundle(CacheKey cacheKey, List candidateLocales, List formats, Int32 index, Control control, ResourceBundle baseBundle)
    at java.util.ResourceBundle.getBundleImpl(String baseName, Locale locale, ClassLoader loader, Control control)
    at java.util.ResourceBundle.getBundle(String baseName, Locale locale, CallerID )`

**Comment by wasabii** [comment]
I suspect this is fixed in https://github.com/ikvm-revived/ikvm/issues/137
