### ISSUE TITLE
Minecraft 1.16.5 (LWJGL 3.3.2) java.lang.InternalError, vague error (?)

### ISSUE THREAD

**Issue by Reimnop** [ikvmnet/ikvm#492]
IKVM version is 8.7.5 from releases on GitHub. Throws the following exception when initializing LWJGL.
Tested with Prism Launcher 8.0, official launcher, as well as when using `IkvmReference` in a .NET 6 project to launch Minecraft. (all same error)

```
java.lang.ExceptionInInitializerError: java.lang.RuntimeException: java.lang.InternalError: java.lang.InternalError: found java.lang.invoke.MethodHandleImpl$BindCaller, expected org.lwjgl.system.Library, or else java.lang.invoke.MethodHandleImpl$BindCaller$T/14967196
	at dkd.<init>(SourceFile:146)
	at djz.<init>(SourceFile:440)
	at net.minecraft.client.main.Main.main(SourceFile:177)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:119)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
	at java.lang.reflect.Method.invoke(Method.java:486)
	at IKVM.Runtime.Accessors.Java.Lang.Reflect.MethodAccessor.InvokeInvoke(MethodAccessor.cs:35)
```

**Comment by Reimnop** [comment]
This didn't happen with IKVM 8.6.4 on JIT, but same bug happens when statically compiled.

**Comment by wasabii** [comment]
Repro by chance?

**Comment by Reimnop** [comment]
I simply attempt to launch Minecraft using the mentioned configuration and that was the error. I couldn't get it to work.

**Comment by wasabii** [comment]
I don't really have anyway to approach this issue without more detailed information or a reproduction. I know nothing about Minecraft. Going to close for now.
