### ISSUE TITLE
QuPath IKVM (8.9.0-PullRequest0528.145) MSB4181 The "IkvmCompiler" task returned false but did not log an error.

### ISSUE THREAD

**Issue by BiologyTools** [ikvmnet/ikvm#546]
I'm trying to get QuPath working with IKVM but I run into an error when trying to convert "qupath-app-0.5.1.jar". Giving me an error: MSB4181 The "IkvmCompiler" task returned false but did not log an error. Here is the output given by IKVM when building:
```
Build started at 7:19...
1>------ Build started: Project: QuPath.NET, Configuration: Release x64 ------
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): warning :
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): warning : *** COMPILER ERROR ***
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): warning :
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): warning : IKVM.Tools.Importer, Version=8.9.0.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): warning : D:\.nuget\ikvm.msbuild.tools.runtime.win-x64\8.9.0-pullrequest0528.145\ikvmc\net8.0\win-x64\
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): warning : 8.0.5 64-bit
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): warning :
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): warning : IKVM.ByteCode.UnsupportedClassVersionException: Unsupported class version 65.0.
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): warning :    at IKVM.ByteCode.Parsing.ClassRecord.TryRead(ClassFormatReader& reader, ClassRecord& clazz) in /_/src/IKVM.ByteCode/Parsing/ClassRecord.cs:line 30
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): warning :    at IKVM.ByteCode.Reading.ClassReader.TryRead(ClassFormatReader& reader, ClassReader& clazz) in /_/src/IKVM.ByteCode/Reading/ClassReader.cs:line 169
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): warning :    at IKVM.ByteCode.Reading.ClassReader.TryRead(ReadOnlySequence`1& buffer, ClassReader& clazz, SequencePosition& consumed, SequencePosition& examined) in /_/src/IKVM.ByteCode/Reading/ClassReader.cs:line 132
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): warning :    at IKVM.ByteCode.Reading.ClassReader.Read(ReadOnlyMemory`1 buffer) in /_/src/IKVM.ByteCode/Reading/ClassReader.cs:line 104
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): warning :    at IKVM.Tools.Importer.IkvmImporterInternal.IsExcludedOrStubLegacy(RuntimeContext context, StaticCompiler compiler, CompilerOptions options, ZipArchiveEntry ze, Byte[] data) in /_/src/IKVM.Tools.Importer/IkvmImporterInternal.cs:line 1219
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): warning :    at IKVM.Tools.Importer.IkvmImporterInternal.ProcessZipFile(RuntimeContext context, StaticCompiler compiler, CompilerOptions options, String file, Predicate`1 filter) in /_/src/IKVM.Tools.Importer/IkvmImporterInternal.cs:line 1277
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): warning :    at IKVM.Tools.Importer.IkvmImporterInternal.ProcessFile(RuntimeContext context, StaticCompiler compiler, CompilerOptions options, DirectoryInfo baseDir, String file) in /_/src/IKVM.Tools.Importer/IkvmImporterInternal.cs:line 1310
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): warning :    at IKVM.Tools.Importer.IkvmImporterInternal.ReadFiles(RuntimeContext context, StaticCompiler compiler, CompilerOptions options, List`1 fileNames) in /_/src/IKVM.Tools.Importer/IkvmImporterInternal.cs:line 1007
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): warning :    at IKVM.Tools.Importer.IkvmImporterInternal.ContinueParseCommandLine(RuntimeContext context, StaticCompiler compiler, IEnumerator`1 arglist, List`1 targets, CompilerOptions options) in /_/src/IKVM.Tools.Importer/IkvmImporterInternal.cs:line 907
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): warning :    at IKVM.Tools.Importer.IkvmImporterInternal.Compile(String[] args) in /_/src/IKVM.Tools.Importer/IkvmImporterInternal.cs:line 174
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): warning :    at IKVM.Tools.Importer.IkvmImporterInternal.Execute(String[] args) in /_/src/IKVM.Tools.Importer/IkvmImporterInternal.cs:line 112
1>D:\.nuget\ikvm\8.9.0-pullrequest0528.145\buildTransitive\IKVM.IkvmReference.Tasks.targets(31,9): error MSB4181: The "IkvmCompiler" task returned false but did not log an error.
1>Done building project "QuPath.NET.csproj" -- FAILED.
```
Here is the IKVMReference I'm using:
```
<IkvmReference Include="qupath-app-0.5.1.jar">
  <AssemblyName>qpath</AssemblyName>
  <AssemblyVersion>0.5.1.0</AssemblyVersion>
  <AssemblyFileVersion>0.5.1.0</AssemblyFileVersion>
  <Compile>turbojpeg-7.0.1.jar;undofx-2.1.1.jar;wellbehavedfx-0.3.3.jar;xercesImpl-2.12.2.jar;xml-apis-1.4.01.jar;xmpcore-6.1.11.jar;aircompressor-0.21.jar;api-0.24.0.jar;base-18.09.0.jar;cdm-core-5.3.3.jar;checker-qual-3.37.0.jar;commonmark-0.21.0.jar;commonmark-ext-yaml-front-matter-0.21.0.jar;commons-compress-1.23.0.jar;commons-io-2.7.jar;commons-lang-2.6.jar;commons-lang3-3.12.0.jar;commons-math3-3.6.1.jar;commons-text-1.10.0.jar;controlsfx-11.1.2.jar;error_prone_annotations-2.21.1.jar;failureaccess-1.0.1.jar;flowless-0.7.2.jar;formats-api-7.0.1.jar;formats-bsd-7.0.1.jar;formats-gpl-7.0.1.jar;groovy-4.0.15.jar;groovy-jsr223-4.0.15.jar;groovy-xml-4.0.15.jar;gson-2.10.1.jar;guava-32.1.3-jre.jar;httpclient-4.5.9.jar;httpmime-4.5.9.jar;httpservices-5.3.3.jar;ij-1.54f.jar;ikonli-core-12.3.1.jar;ikonli-ionicons4-pack-12.3.1.jar;ikonli-javafx-12.3.1.jar;jackson-annotations-2.14.2.jar;jackson-core-2.14.2.jar;jackson-databind-2.14.2.jar;javacpp-1.5.9.jar;javacpp-1.5.9-windows-x86_64.jar;javacpp-platform-1.5.8.jar;javafx-base-20-win.jar;javafx-controls-20-win.jar;javafx-fxml-20-win.jar;javafx-graphics-20-win.jar;javafx-media-20-win.jar;javafx-swing-20-win.jar;javafx-web-20-win.jar;jfxtras-common-17-r1.jar;jfxtras-menu-17-r1.jar;jgoodies-common-1.7.0.jar;jgoodies-forms-1.7.2.jar;jhdf5-19.04.0.jar;jna-5.13.0.jar;joda-time-2.12.2.jar;json-20230227.jar;jsr305-3.0.2.jar;jts-core-1.19.0.jar;jxrlib-all-0.2.4.jar;kryo-5.4.0.jar;listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;logback-classic-1.3.11.jar;logback-core-1.3.11.jar;logviewer-api-0.1.1.jar;logviewer-logging-logback-0.1.1.jar;logviewer-ui-main-0.1.1.jar;logviewer-ui-richtextfx-0.1.1.jar;logviewer-ui-textarea-0.1.1.jar;metadata-extractor-2.18.0.jar;metakit-5.3.5.jar;minlog-1.3.1.jar;native-lib-loader-2.4.0.jar;objenesis-3.3.jar;ome-codecs-1.0.0.jar;ome-common-6.0.20.jar;ome-jai-0.1.3.jar;ome-mdbtools-5.3.2.jar;ome-poi-5.3.7.jar;ome-xml-6.3.3.jar;openblas-0.3.21-1.5.8.jar;openblas-0.3.21-1.5.8-windows-x86_64.jar;openblas-platform-0.3.21-1.5.8.jar;opencv-4.6.0-1.5.8.jar;opencv-4.6.0-1.5.8-windows-x86_64.jar;opencv-platform-4.6.0-1.5.8.jar;openslide-4.0.0-win32-x86_64.jar;org.jfree.svg-5.0.5.jar;perf4j-0.9.16.jar;picocli-4.7.5.jar;protobuf-java-3.23.3.jar;pytorch-engine-0.24.0.jar;pytorch-model-zoo-0.24.0.jar;qupath-app-0.5.1.jar;qupath-bioimageio-spec-0.1.0.jar;qupath-core-0.5.1.jar;qupath-core-processing-0.5.1.jar;qupath-extension-bioformats-0.5.1.jar;qupath-extension-openslide-0.5.1.jar;qupath-extension-processing-0.5.1.jar;qupath-extension-script-editor-0.5.1.jar;qupath-extension-svg-0.5.1.jar;qupath-fxtras-0.1.4.jar;qupath-gui-fx-0.5.1.jar;re2j-1.3.jar;reactfx-2.0-M5.jar;reflectasm-1.11.9.jar;richtextfx-0.11.2.jar;slf4j-api-2.0.9.jar;snakeyaml-2.2.jar;specification-6.3.3.jar;sqlite-jdbc-3.28.0.jar;tensorflow-api-0.24.0.jar;tensorflow-engine-0.24.0.jar;tensorflow-model-zoo-0.24.0.jar</Compile>
</IkvmReference>
```
Does anyone know what the issue could be?

**Comment by wasabii** [comment]
Please test again with 8.9.0-pre.1.

**Comment by wasabii** [comment]
This should be resolved.
