### ISSUE TITLE
IKVM Closure Compiler .jar to .exe Conversion

### ISSUE THREAD

**Issue by wessleym** [ikvmnet/ikvm#584]
In old versions of IKVM, I used to be able to call IKVM like this:
`ikvmc closure-compiler-vYYYYMMDD.jar`
An executable would be produced.
From what I understand, it is no longer reasonably possible to call ikvmc directly because the user must specify certain .NET assemblies explicitly. So I tried making a project in Visual Studio:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IKVM" Version="8.10.1" />
  </ItemGroup>

  <ItemGroup>
	<IkvmReference Include="../../ext/closure-compiler-v20240317.jar">
	  <AssemblyName>closure-compiler-v20240317</AssemblyName>
	</IkvmReference>
  </ItemGroup>

</Project>

```
When I build, I see a new .dll in my project directory. But I am hoping to get a .exe file so I can execute it. Is it still possible to output a .exe file? Or is it possible to execute this .dll file somehow? (I did try adding a .runtime.config.json file, but I just got this exception: "Unhandled exception. System.MissingMethodException: Entry point not found in assembly...") Thank you.

**Comment by wasabii** [comment]
You could use IKVM.NET.Sdk to produce an executable, but that is not very typical. Generally the point of our MSBuild integration is for developers intending to consume a Java library.

Producing an .exe isn't as easy as it once once, because there is no such thing as a .NET exe in .NET Core. .NET Core only supports building DLLs and executing them either with the dotnet.exe tool, or by wrapping it with apphost exe distributed by the .EXE.

And generally people who just want to run Java programs can just execute our version of javac.exe.

**Comment by wessleym** [comment]
Thank you, @wasabii, for your fast reply and for all your work on this project.
I would be interested if you could further explain your first sentence and how I could use IKVM.NET.Sdk to make an executable.
I wouldn't mind running java.exe on closure-compiler-v20240317.jar, but it fails. I execute this:
`.\java closure-compiler-v20240317.jar`
And here is the result:
`Error: Could not find or load main class closure-compiler-v20240317.jar`

**Comment by wasabii** [comment]
Our java.exe functions exactly like any other. That's not how you run a jar with java.exe. You specify either -cp and the main class, or -jar.

**Comment by wasabii** [comment]
>I would be interested if you could further explain your first sentence and how I could use IKVM.NET.Sdk to make an executable.

https://www.nuget.org/packages/IKVM.NET.Sdk/8.10.1#readme-body-tab

IKVM.NET.Sdk is a SDK project type for MSBuild which functions like Microsoft.NET.Sdk, except takes Java artifacts as input instead of CSharp files. So you can create a IKVM.NET.Sdk project file, set up your TFMs, and *.java files are included automatically. But you can also add various other ItemGroups to incorporate other Java resources: and the `Convert` itemgroup lets you extract .class files out of a .jar file.

**Comment by wessleym** [comment]
Regarding calling java.exe, I should have mentioned that I previously tried that as well:
`.\java -jar closure-compiler-v20240317.jar`
```
Exception in thread "Thread-0" java.lang.UnsupportedClassVersionError: 55.0
        at IKVM.Java.Externs.java.lang.ClassLoader.DefineClass(ClassLoader.cs:152)
        at IKVM.Java.Externs.java.lang.ClassLoader.defineClass1(ClassLoader.cs:89)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:774)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(AccessController.java:310)
        at java.security.AccessController.doPrivileged(AccessController.java:718)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:438)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:371)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:621)
        at IKVM.Runtime.Accessors.Sun.Launcher.LauncherHelperAccessor.InvokeCheckAndLoadMain(Unknown Source)
```
I wonder if this has something with JDK 9 support.
The IKVM.NET.Sdk approach does sound complicated since I'll apparently be extracting classes instead of just converting the .jar file to a .exe file. But thank you for that information.

**Comment by wasabii** [comment]
We do not support anything beyond JDK8 presently. And yes, that error indicates there is a class for JDK9+ being loaded.

**Comment by wasabii** [comment]
>The IKVM.NET.Sdk approach does sound complicated since I'll apparently be extracting classes instead of just converting the .jar file to a .exe file. But thank you for that information.

To clarify here, when you include .class files as a resource (separately or in a .jar file) in IKVM.NET.Sdk, they are fed to the static compiler when producing the output assembly. It produces an assembly. It does NOT produce an executable in .NET Core TFMs, because in .NET Core there is no such concept beyond apphost.exe

**Comment by wessleym** [comment]
You probably get asked this all the time, but do you intend to support newer JDK versions?
As for the .exe, right. I keep saying .exe, but I understand it might need to be a .NET .dll I can execute by calling dotnet.exe (or something like that).

I have downgraded to an older version of Closure Compiler from June of 2022. When I execute it with your java.exe, it pauses and then says this:
```
java.lang.NoSuchMethodError: java.nio.file.Files.readString(Ljava.nio.file.Path;Ljava.nio.charset.Charset;)Ljava.lang.String;
        at com.google.javascript.jscomp.SourceFile$CodeLoader$OnDisk.loadUncachedCode(SourceFile.java:713)
        at com.google.javascript.jscomp.SourceFile.getCode(SourceFile.java:152)
        at com.google.javascript.jscomp.CompilerInput.getCode(CompilerInput.java:509)
        at com.google.javascript.jscomp.CompilerInput.generateDependencyInfo(CompilerInput.java:312)
        at com.google.javascript.jscomp.CompilerInput.getDependencyInfo(CompilerInput.java:273)
        at com.google.javascript.jscomp.CompilerInput.getProvides(CompilerInput.java:190)
        at com.google.javascript.jscomp.Compiler.findModulesFromEntryPoints(Compiler.java:2017)
        at com.google.javascript.jscomp.Compiler.parseInputs(Compiler.java:1846)
        at com.google.javascript.jscomp.Compiler.parseForCompilationInternal(Compiler.java:1096)
        at com.google.javascript.jscomp.Compiler.lambda$parseForCompilation$9(Compiler.java:1080)
        at com.google.javascript.jscomp.CompilerExecutor.lambda$runInCompilerThread$0(CompilerExecutor.java:101)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:978)
```
Thank you.

**Comment by wasabii** [comment]
#120

Oh yeah. There's still so much to clean up though. It took me two years just to get the latest version of JDK8 working.

This is an interesting error. It's refering to a method, java.nio.file.Files.readString, which looks like it was new in JDK9: https://docs.oracle.com/en%2Fjava%2Fjavase%2F11%2Fdocs%2Fapi%2F%2F/java.base/java/nio/file/Files.html#readString(java.nio.file.Path,java.nio.charset.Charset)

But it doesn't fail to load the class. So, it looks like this version of Closure is built targeting a down-level class file format version (48), but was compiled against the JDK11 API. So, it's missing a method. We're choice of theirs to target a down level class file format version when they reference classes that don't exist at that time.

**Comment by wessleym** [comment]
@wasabii, I see. Thank you again for your work on this project and for helping me!
