### ISSUE TITLE
Error when using Java program with GUI(AWT) on arm64 ikvm for net472 on some Arm-based Windows 11 24H2

### ISSUE THREAD

**Issue by kdaek21** [ikvmnet/ikvm#628]
I have two Arm-based Windows devices.
One is Galaxy Book2 (SM-W737 model) and the other is Galaxy Book Edge (NT960XMB-KC01B model) that was recently released.

Galaxy Book2 is an old device that was released recently, so it was Windows 11 23H2 until recently, and recently upgraded to Windows 11 24H2. Galaxy Book Edge was released as Copilot+PC from the time of release, although it was updated recently, so it was released as Windows 11 24H2.

When trying to run a Java program using AWT using ikvm-8.10.3-net472-arm64 on a Galaxy Book 2 updated to Windows 11 24H2, an error occurs regarding the awt.dll file in the ikvm folder. (The same error occurs when trying to run a program that uses Swing, not AWT, and I have not confirmed whether it worked normally before updating to Windows 11 24H2.)
* It works normally without any errors on the Galaxy Book Edge.

The specifications for each are as follows.
CPU: Galaxy Book 2 - Qualcomm Snapdragon 850 / Galaxy Book Edge - Qualcomm Snapdragon X Elite
RAM: Galaxy Book 2 - 4GB / Galaxy Book Edge - 16GB

The error message is as follows. Is it a compatibility issue between the CPU (or the entire device) and the updated Windows (will it be resolved with a future Windows update?)?
* The Java in the path in the error message is the unzipped folder of ikvm-jre8-8.10.3-net472-arm64. (I tried to shorten it because I thought it might be an issue caused by the path name being too long, but the same error occurred.)

Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: C:\Java\bin\awt.dll: %1 is not a valid Win32 application.

        at java.lang.reflect.Constructor.newInstance(Constructor.java:413)
        at IKVM.Runtime.LibJvm.JVM_ThrowException(LibJVM.cs:204)
        at IKVM.Runtime.LibJvm.JVM_LoadLibrary(LibJVM.cs:550)
        at IKVM.Runtime.JNI.JNINativeLoader.LoadLibrary(JNINativeLoader.cs:62)
        at IKVM.Java.Externs.java.lang.ClassLoader+NativeLibrary.load(ClassLoader.NativeLibrary.cs:106)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1936)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1840)
        at java.lang.Runtime.loadLibrary0(Runtime.java:844)
        at java.lang.System.loadLibrary(System.java:1158)
        at java.awt.Toolkit$3.run(Toolkit.java:1637)
        at java.awt.Toolkit$3.run(Toolkit.java:1634)
        at java.security.AccessController.doPrivileged(AccessController.java:308)
        at java.security.AccessController.doPrivileged(AccessController.java:356)
        at java.awt.Toolkit.loadLibraries(Toolkit.java:1633)
        at java.awt.Toolkit.<clinit>(Toolkit.java:1671)
        at java.awt.Toolkit.loadLibraries(Toolkit.java)
        at java.awt.Component.<clinit>(Component.java:595)
        at java.awt.Container.<clinit>(Container.java:96)
        at java.awt.Window.<clinit>(Window.java:225)
        at java.awt.Frame.<clinit>(Frame.java:359)
        at cli.System.Runtime.CompilerServices.RuntimeHelpers._RunClassConstructor(Unknown Source)
        at IKVM.Runtime.RuntimeJavaType.RunClassInit(RuntimeJavaType.cs:1240)

**Comment by wasabii** [comment]
So, same as with other reply.

Just to let you know, I don't have any Windows ARM environments to test any of this. I've been releasing it blind, but running unit tests on a Github ARM machine automated pipeline. I've never SEEN it work.

**Comment by kdaek21** [comment]
This also seems to be due to the same problem as #627, which is that awt.dll could not be loaded. After resolving #627, I also confirmed that AWT and Swing programs work normally in the net472 version.

It seems that Readme.md needs to be updated for the following reasons:
* How to use ikvmc directly based on the current version
* (For Windows) Guide to installing the latest VC++ redistributable package
* Updated description of Compile and Sources tags in IkvmReference (I know it is available now, but 'not yet supported' remains)
* Others..

**Comment by wasabii** [comment]
Feel free to submit pull requests. The documentation is a serious issue, but I'm pretty much the only person working on this project.... so, yeah. Not a thing I'm focused on.
