### ISSUE TITLE
TypeLoadException Type is attempting to implement an inaccessible interface

### ISSUE THREAD

**Issue by AliveDevil** [ikvmnet/ikvm#635]
Failing code:

https://github.com/aws/aws-sdk-java/blob/1.12.778/aws-java-sdk-core/src/main/java/com/amazonaws/http/conn/ClientConnectionManagerFactory.java#L54-L58

```
java.lang.Throwable: Exception during finishing of: com.amazonaws.http.conn.$Proxy17
	at IKVM.Runtime.RuntimeByteCodeJavaType+JavaTypeImpl.FinishCore(Unknown Source) ~[?:?]
	at IKVM.Runtime.RuntimeByteCodeJavaType+JavaTypeImpl.Finish(Unknown Source) ~[?:?]
	at IKVM.Runtime.RuntimeByteCodeJavaType.Finish(Unknown Source) ~[?:?]
	at IKVM.Java.Externs.java.lang.Class.getDeclaredConstructors0(Unknown Source) ~[?:?]
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2674) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3078) ~[?:?]
	at java.lang.Class.getConstructor(Class.java:1856) ~[?:?]
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:729) ~[?:?]
	at com.amazonaws.http.conn.ClientConnectionManagerFactory.wrap(ClientConnectionManagerFactory.java:54) ~[Cyberduck.Protocols.dll:?]
	at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:56) ~[Cyberduck.Protocols.dll:?]
	at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:38) ~[Cyberduck.Protocols.dll:?]
	at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:356) ~[Cyberduck.Protocols.dll:?]
```

Classloader: AppDomainAssemblyClassLoader

**Comment by AliveDevil** [comment]
More context in stack trace:
<details>

```
  IKVM.Runtime.InternalException: Exception during finishing of: com.amazonaws.http.conn.$Proxy21 ---> System.TypeLoadException: Type 'com.amazonaws.http.conn.$Proxy21' from assembly 'ikvm_dynamic_assembly__18161828, Version=2024.1216.1622.20024, Culture=neutral, PublicKeyToken=null' is attempting to implement an inaccessible interface.
  Stapelüberwachung:
        at System.Reflection.Emit.RuntimeTypeBuilder.CreateTypeNoLock()
    um System.Reflection.Emit.RuntimeTypeBuilder.CreateTypeInfoImpl()
    um System.Reflection.Emit.TypeBuilder.CreateType()
    um IKVM.Runtime.RuntimeByteCodeJavaType.FinishContext.FinishImpl()
    um IKVM.Runtime.RuntimeByteCodeJavaType.JavaTypeImpl.FinishCore()
    --- End of inner exception stack trace ---
        at IKVM.Runtime.RuntimeByteCodeJavaType.JavaTypeImpl.FinishCore()
    um IKVM.Runtime.RuntimeByteCodeJavaType.JavaTypeImpl.Finish()
    um IKVM.Runtime.RuntimeByteCodeJavaType.Finish()
    um IKVM.Java.Externs.java.lang.Class.getDeclaredConstructors0(Class thisClass, Boolean publicOnly)
    um java.lang.Class.privateGetDeclaredConstructors(Boolean publicOnly)
    um java.lang.Class.getConstructor0(Class[] parameterTypes, Int32 which)
    um java.lang.Class.getConstructor(Class[] parameterTypes, CallerID)
    um java.lang.reflect.Proxy.newProxyInstance(ClassLoader loader, Class[] interfaces, InvocationHandler h, CallerID)
    um com.amazonaws.http.conn.ClientConnectionManagerFactory.wrap(HttpClientConnectionManager orig)
    um com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(HttpClientSettings settings)
    um com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.<bridge>create(HttpClientSettings hcs)
    um com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.__<overridestub>com.amazonaws.http.client.HttpClientFactory::create(HttpClientSettings)
    um com.amazonaws.http.AmazonHttpClient..ctor(ClientConfiguration config, RetryPolicy retryPolicy, RequestMetricCollector requestMetricCollector, Boolean useBrowserCompatibleHostNameVerifier, Boolean calculateCRC32FromCompressedData)
    um com.amazonaws.http.AmazonHttpClient..ctor(ClientConfiguration config, RequestMetricCollector requestMetricCollector, Boolean useBrowserCompatibleHostNameVerifier, Boolean calculateCRC32FromCompressedData)
    um com.amazonaws.AmazonWebServiceClient..ctor(AwsSyncClientParams clientParams, Boolean useStrictHostNameVerification)
    um com.amazonaws.AmazonWebServiceClient..ctor(AwsSyncClientParams clientParams)
    um com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient..ctor(AwsSyncClientParams clientParams, Boolean endpointDiscoveryEnabled)
    um com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient..ctor(AwsSyncClientParams clientParams)
    um com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.build(AwsSyncClientParams params)
    um com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.<bridge>build(AwsSyncClientParams ascp)
    um com.amazonaws.client.builder.AwsSyncClientBuilder.build()
```

</details>

**Comment by AliveDevil** [comment]
This occurs when `-Static`-compiling with `AppDomainAssemblyClassLoader`.

**Comment by wasabii** [comment]
So, to recap discussion on Discord.

-static apparently means "do not do anything that would require dynamic code gen". Proxies would require dynamic code gen. Either the -static feature needs to be implemented in tandem with the -proxy feature (which needs to be fixed itself), or the code needs to not use proxies.
